### ISSUE TITLE
about baseline

### ISSUE THREAD

**Issue by clytze0216** [shengyuzhang/DeVLBert#1]
Thanks for your sharing!
I would like to ask if you have tried to apply this to other single-stream baseline, such as UNITER ?
Looking forward to your reply ,thanks again

**Comment by shengyuzhang** [comment]
Hi, Thanks for your attention on our work. In the very early stage of our work, UNITER is one of the considered baselines. However, the codebase of UNITER released in that time (especially codes concerning the downstream evaluations) is not as comprehensive as the ViLBert. We didn't try to apply the proposed method to UNITER afterwards but we think it should be significant since UNITER yields better performance. It is also quite workable since our method can be architecture-agnostic and non-intrusive.

**Comment by clytze0216** [comment]
@shengyuzhang 
Thanks for your kindly reply!
I  still have a lot to learn, because I'm new here.
Therefore, I would like to ask you whether it is possible to apply DeVl based on the existing codebase of UNITER
Looking forward to your reply ,thanks a lot !
